if ENV['USE_OFFICIAL_GEM_SOURCE']
  source 'http://rubygems.org'
else
  source 'https://ruby.taobao.org'
end
gem 'rails', '4.1.7'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.3'
gem 'bootstrap-sass'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'devise'
gem 'slim'
gem 'slim-rails'
gem 'migration_comments', '~> 0.3'
gem 'simple_form'
gem 'thin'
gem 'flash_render'
gem 'ransack'
